# Importing necessary libraries

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Loading The Raw Data

In [2]:
Raw_Data = open("../data/Raw_Data1.txt","r") 
#Opens the text file in readable format

In [3]:
content = Raw_Data.read() #reading the file 
Raw_list = content.split() # converts the sequences into a list for easier iteration

In [4]:
DF = pd.DataFrame({
    'Serial_No': range(1, len(Raw_list)+1),
    'DNA_Sample': Raw_list,
})
#Creating a DataFrame as a base for the DNA Samples

# Writing detector block for each disease

In [5]:
def check(sequence, motif):
    max_count = 0 
    count = 0
    i = 0
    while i <= len(sequence) - len(motif): #consider the length of the pattern too 
        if sequence[i:i + len(motif)] == motif: #condition to match pattern(different for each disease 
            count += 1
            i += len(motif)
            max_count = max(max_count, count)
        else:
            count = 0
            i += 1
    return max_count

In [6]:
'''
each column for a disease is preset to none 
if the sample contains the disese the column says 'Found' 
the count of repetitions is given in the column next to it 
'''

"\neach column for a disease is preset to none \nif the sample contains the disese the column says 'Found' \nthe count of repetitions is given in the column next to it \n"

### Code block for Huntington's Disease

In [7]:
# 1.Huntington's Disease
DF['Huntington\'s_Disease'] = "Not Found" #column to hold boolean value

In [8]:
DF['HD_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CAG')
    if max_count >= 36:
        DF.at[idx, 'HD_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Huntington\'s_Disease'] = "Found"

### Code block for Fragile x syndrome

In [9]:
# 2.Fragilexsyndrome
DF['Fragile_x_syndrome'] = "Not Found" #column to hold boolean value

In [10]:
DF['FXS_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CGG')
    if max_count >= 200:
        DF.at[idx, 'FXS_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Fragile_x_syndrome'] = "Found"

### Code block for Myotonic dystophy

In [11]:
# 3.Myotonic dystophy
DF['Myotonic_dystophy'] = "Not Found" #column to hold boolean value

In [12]:
DF['MD_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CTG')
    if max_count >= 50:
        DF.at[idx, 'MD_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Myotonic_dystophy'] = "Found"

### Code block for Dentatorubral-Pallidoluysian Atrophy

In [13]:
# 4.Dentatorubral-Pallidoluysian Atrophy
DF['Dentatorubral-PA'] = "Not Found" #column to hold boolean value

In [14]:
DF['DPA_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CAG')
    if max_count >= 40:
        DF.at[idx, 'DPA_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Dentatorubral-PA'] = "Found"

### Code block for Friedreich’s Ataxia

In [15]:
# 5.Friedreich’s Ataxia
DF['Friedreich’s_Ataxia'] = "Not Found" #column to hold boolean value

In [16]:
DF['FA_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='GAA')
    if max_count >= 66:
        DF.at[idx, 'FA_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Friedreich’s_Ataxia'] = "Found"

### Code block for Ataxia Syndrome (FXTAS)

In [17]:
# 6.Ataxia Syndrome
DF['Ataxia_Syndrome'] = "Not Found" #column to hold boolean value

In [18]:
DF['AS repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CGG')
    if max_count >= 55:
        DF.at[idx, 'AS_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Ataxia_Syndrome'] = "Found"

### Code block for Oculopharyngeal Muscular Dystrophy (OPMD)

In [19]:
# 7.Oculopharyngeal Muscular Dystrophy
DF['OPMD'] = "Not Found" #column to hold boolean value

In [20]:
DF['OPMD_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='GGC')
    if max_count >= 8:
        DF.at[idx, 'OPMD_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'OPMD'] = "Found"

### Code block for Spinocerebellar Ataxia Type 8

In [21]:
# 8.Spinocerebellar Ataxia Type 8
DF['Spinocerebellar_Ataxia_Type8'] = "Not Found" #column to hold boolean value

In [22]:
DF['SA8_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CAG')
    if max_count >= 70:
        DF.at[idx, 'SA8_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Spinocerebellar_Ataxia_Type8'] = "Found"

### Code block for Spinocerebellar Ataxia Type 4

In [23]:
# 9.Spinocerebellar Ataxia Type 4
DF['Spinocerebellar_Ataxia_Type4'] = "Not Found" #column to hold boolean value

In [24]:
DF['SA4 repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='CAG')
    if 40 <= max_count <=80:
        DF.at[idx, 'SA4_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Spinocerebellar_Ataxia_Type4'] = "Found"

### Code block for Frontotemporal Dementia

In [25]:
# 10.Frontotemporal Dementia
DF['Frontotemporal_Dementia'] = "Not Found" #column to hold boolean value

In [26]:
DF['FD_repetitions'] = np.nan  # Create empty column

for idx, row in DF.iterrows():
    sequence = row['DNA_Sample']
    max_count = check(sequence, motif='GGGGCC')
    if max_count >= 30:
        DF.at[idx, 'FD_repetitions'] = max_count  # Pathogenic repeat count
        DF.at[idx, 'Frontotemporal_Dementia'] = "Found"

# Final DATAFRAME

In [27]:
DF

,Serial_No,DNA_Sample,Huntington's_Disease,HD_repetitions,Fragile_x_syndrome,FXS_repetitions,Myotonic_dystophy,MD_repetitions,Dentatorubral-PA,DPA_repetitions,...,AS_repetitions,OPMD,OPMD_repetitions,Spinocerebellar_Ataxia_Type8,SA8_repetitions,Spinocerebellar_Ataxia_Type4,SA4 repetitions,SA4_repetitions,Frontotemporal_Dementia,FD_repetitions
0,1,GATAGGAACAGCCACTAGACCTCTGGTTGGTACCGTTACACGCGGT...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,68.0,Found,67.0,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
1,2,AGGTTAGCTAGCCTATAGCTCGCGACCTATGTGGGAGACTAGAGCT...,Not Found,NaN,Not Found,NaN,Found,67.0,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
2,3,ACAATGAGCCGTCAACGAGCTCGACGAGTTCGACAACGAATTATCC...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Found,76.0
3,4,AACCTGGTCCCCCTCCGAAGCTAAAGGGAATTGGACGTCGAGTAGG...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Found,70.0
4,5,TCACGCTGCCTGGGAGAGCATATGAGCAGACAGCGTGTCAAGAGCG...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,ACGAGAATGCGTAATTACCGTGATCACAATATTCTGAGCAGTTCTC...,Found,85.0,Not Found,NaN,Not Found,NaN,Found,85.0,...,NaN,Not Found,NaN,Found,85.0,Not Found,NaN,NaN,Not Found,NaN
3996,3997,TATCGTGCTGACTGCTCTATACCCCTGTAAGAAATTGTTATTACGT...,Not Found,NaN,Not Found,NaN,Found,61.0,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3997,3998,TGGAATCAAAGCATTCGTACCCGAACTGAGATCTCGCACGGCTTAC...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3998,3999,GTGTACAGTGCGGGAGATGGGAAGGACTCCTAAAACGAGCCTCCGC...,Not Found,NaN,Found,239.0,Not Found,NaN,Not Found,NaN,...,239.0,Found,238.0,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3999,4000,AGCGGGTACCCCGGCAACGAGTCGTCGATGAACTACCTACAGCAGC...,Found,72.0,Not Found,NaN,Not Found,NaN,Found,72.0,...,NaN,Not Found,NaN,Found,72.0,Found,NaN,72.0,Not Found,NaN

# Saving as a CSV file for further preprocessing

In [28]:
DF.to_csv("../data/results.csv", index = False)

---------------------------------------------------------------------------------------------------------------------------------------------------------

# Loading the Dataset

In [30]:
data = pd.read_csv("../data/results.csv")

In [31]:
data

,Serial_No,DNA_Sample,Huntington's_Disease,HD_repetitions,Fragile_x_syndrome,FXS_repetitions,Myotonic_dystophy,MD_repetitions,Dentatorubral-PA,DPA_repetitions,...,AS_repetitions,OPMD,OPMD_repetitions,Spinocerebellar_Ataxia_Type8,SA8_repetitions,Spinocerebellar_Ataxia_Type4,SA4 repetitions,SA4_repetitions,Frontotemporal_Dementia,FD_repetitions
0,1,GATAGGAACAGCCACTAGACCTCTGGTTGGTACCGTTACACGCGGT...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,68.0,Found,67.0,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
1,2,AGGTTAGCTAGCCTATAGCTCGCGACCTATGTGGGAGACTAGAGCT...,Not Found,NaN,Not Found,NaN,Found,67.0,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
2,3,ACAATGAGCCGTCAACGAGCTCGACGAGTTCGACAACGAATTATCC...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Found,76.0
3,4,AACCTGGTCCCCCTCCGAAGCTAAAGGGAATTGGACGTCGAGTAGG...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Found,70.0
4,5,TCACGCTGCCTGGGAGAGCATATGAGCAGACAGCGTGTCAAGAGCG...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,ACGAGAATGCGTAATTACCGTGATCACAATATTCTGAGCAGTTCTC...,Found,85.0,Not Found,NaN,Not Found,NaN,Found,85.0,...,NaN,Not Found,NaN,Found,85.0,Not Found,NaN,NaN,Not Found,NaN
3996,3997,TATCGTGCTGACTGCTCTATACCCCTGTAAGAAATTGTTATTACGT...,Not Found,NaN,Not Found,NaN,Found,61.0,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3997,3998,TGGAATCAAAGCATTCGTACCCGAACTGAGATCTCGCACGGCTTAC...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3998,3999,GTGTACAGTGCGGGAGATGGGAAGGACTCCTAAAACGAGCCTCCGC...,Not Found,NaN,Found,239.0,Not Found,NaN,Not Found,NaN,...,239.0,Found,238.0,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3999,4000,AGCGGGTACCCCGGCAACGAGTCGTCGATGAACTACCTACAGCAGC...,Found,72.0,Not Found,NaN,Not Found,NaN,Found,72.0,...,NaN,Not Found,NaN,Found,72.0,Found,NaN,72.0,Not Found,NaN

In [32]:
data.shape #Gives the dimensions of csv file

(4000, 24)

In [33]:
data.info() #Gives us basic information of the data

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 24 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Serial_No                     4000 non-null   int64
 1   DNA_Sample                    4000 non-null   object
 2   Huntington's_Disease          4000 non-null   object
 3   HD_repetitions                1456 non-null   float64
 4   Fragile_x_syndrome            4000 non-null   object
 5   FXS_repetitions               343 non-null    float64
 6   Myotonic_dystophy             4000 non-null   object
 7   MD_repetitions                355 non-null    float64
 8   Dentatorubral-PA              4000 non-null   object
 9   DPA_repetitions               1425 non-null   float64
 10  Friedreich’s_Ataxia           4000 non-null   object
 11  FA_repetitions                402 non-null    float64
 12  Ataxia_Syndrome               4000 non-null   object
 13  AS repetitions                0 non-null      float64
 14  AS_repetitions                704 non-null    float64
 15  OPMD                          4000 non-null   object
 16  OPMD_repetitions              1025 non-null   float64
 17  Spinocerebellar_Ataxia_Type8  4000 non-null   object
 18  SA8_repetitions               782 non-null    float64
 19  Spinocerebellar_Ataxia_Type4  4000 non-null   object
 20  SA4 repetitions               0 non-null      float64
 21  SA4_repetitions               947 non-null    float64
 22  Frontotemporal_Dementia       4000 non-null   object
 23  FD_repetitions                388 non-null    float64
dtypes: float64(12), int64(1), object(11)
memory usage: 750.1+ KB

In [34]:
data.head() #Prints first few lines of the datset

,Serial_No,DNA_Sample,Huntington's_Disease,HD_repetitions,Fragile_x_syndrome,FXS_repetitions,Myotonic_dystophy,MD_repetitions,Dentatorubral-PA,DPA_repetitions,...,AS_repetitions,OPMD,OPMD_repetitions,Spinocerebellar_Ataxia_Type8,SA8_repetitions,Spinocerebellar_Ataxia_Type4,SA4 repetitions,SA4_repetitions,Frontotemporal_Dementia,FD_repetitions
0,1,GATAGGAACAGCCACTAGACCTCTGGTTGGTACCGTTACACGCGGT...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,68.0,Found,67.0,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
1,2,AGGTTAGCTAGCCTATAGCTCGCGACCTATGTGGGAGACTAGAGCT...,Not Found,NaN,Not Found,NaN,Found,67.0,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
2,3,ACAATGAGCCGTCAACGAGCTCGACGAGTTCGACAACGAATTATCC...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Found,76.0
3,4,AACCTGGTCCCCCTCCGAAGCTAAAGGGAATTGGACGTCGAGTAGG...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Found,70.0
4,5,TCACGCTGCCTGGGAGAGCATATGAGCAGACAGCGTGTCAAGAGCG...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN

In [35]:
data.tail() # Gives us last few lines of the code

,Serial_No,DNA_Sample,Huntington's_Disease,HD_repetitions,Fragile_x_syndrome,FXS_repetitions,Myotonic_dystophy,MD_repetitions,Dentatorubral-PA,DPA_repetitions,...,AS_repetitions,OPMD,OPMD_repetitions,Spinocerebellar_Ataxia_Type8,SA8_repetitions,Spinocerebellar_Ataxia_Type4,SA4 repetitions,SA4_repetitions,Frontotemporal_Dementia,FD_repetitions
3995,3996,ACGAGAATGCGTAATTACCGTGATCACAATATTCTGAGCAGTTCTC...,Found,85.0,Not Found,NaN,Not Found,NaN,Found,85.0,...,NaN,Not Found,NaN,Found,85.0,Not Found,NaN,NaN,Not Found,NaN
3996,3997,TATCGTGCTGACTGCTCTATACCCCTGTAAGAAATTGTTATTACGT...,Not Found,NaN,Not Found,NaN,Found,61.0,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3997,3998,TGGAATCAAAGCATTCGTACCCGAACTGAGATCTCGCACGGCTTAC...,Not Found,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,...,NaN,Not Found,NaN,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3998,3999,GTGTACAGTGCGGGAGATGGGAAGGACTCCTAAAACGAGCCTCCGC...,Not Found,NaN,Found,239.0,Not Found,NaN,Not Found,NaN,...,239.0,Found,238.0,Not Found,NaN,Not Found,NaN,NaN,Not Found,NaN
3999,4000,AGCGGGTACCCCGGCAACGAGTCGTCGATGAACTACCTACAGCAGC...,Found,72.0,Not Found,NaN,Not Found,NaN,Found,72.0,...,NaN,Not Found,NaN,Found,72.0,Found,NaN,72.0,Not Found,NaN

In [36]:
data.count() #Tells us about the different parameters or column's counts

Serial_No                       4000
DNA_Sample                      4000
Huntington's_Disease            4000
HD_repetitions                  1456
Fragile_x_syndrome              4000
FXS_repetitions                  343
Myotonic_dystophy               4000
MD_repetitions                   355
Dentatorubral-PA                4000
DPA_repetitions                 1425
Friedreich’s_Ataxia             4000
FA_repetitions                   402
Ataxia_Syndrome                 4000
AS repetitions                     0
AS_repetitions                   704
OPMD                            4000
OPMD_repetitions                1025
Spinocerebellar_Ataxia_Type8    4000
SA8_repetitions                  782
Spinocerebellar_Ataxia_Type4    4000
SA4 repetitions                    0
SA4_repetitions                  947
Frontotemporal_Dementia         4000
FD_repetitions                   388
dtype: int64

In [37]:
data.max() #Returns max value from each column

Serial_No                                                                    4000
DNA_Sample                      TTTTTCAACCTTGATATACCAAATTCTTCGATATGCGTTTGCTAGA...
Huntington's_Disease                                                    Not Found
HD_repetitions                                                              120.0
Fragile_x_syndrome                                                      Not Found
FXS_repetitions                                                             250.0
Myotonic_dystophy                                                       Not Found
MD_repetitions                                                              100.0
Dentatorubral-PA                                                        Not Found
DPA_repetitions                                                             120.0
Friedreich’s_Ataxia                                                     Not Found
FA_repetitions                                                              117.0
Ataxia_Syndrome                                                         Not Found
AS repetitions                                                                NaN
AS_repetitions                                                              250.0
OPMD                                                                    Not Found
OPMD_repetitions                                                            251.0
Spinocerebellar_Ataxia_Type8                                            Not Found
SA8_repetitions                                                             120.0
Spinocerebellar_Ataxia_Type4                                            Not Found
SA4 repetitions                                                               NaN
SA4_repetitions                                                              80.0
Frontotemporal_Dementia                                                 Not Found
FD_repetitions                                                               80.0
dtype: object

In [38]:
data.describe() #summarizes the data

,Serial_No,HD_repetitions,FXS_repetitions,MD_repetitions,DPA_repetitions,FA_repetitions,AS repetitions,AS_repetitions,OPMD_repetitions,SA8_repetitions,SA4 repetitions,SA4_repetitions,FD_repetitions
count,4000.000000,1456.000000,343.000000,355.000000,1425.000000,402.000000,0.0,704.000000,1025.000000,782.000000,0.0,947.000000,388.000000
mean,2000.500000,71.134615,225.279883,74.830986,71.864561,92.201493,NaN,149.563920,111.885854,85.808184,NaN,61.267159,53.626289
std,1154.844867,19.352466,14.702223,14.710565,18.910360,14.549998,NaN,75.390827,83.431915,12.562837,NaN,11.864519,15.258226
min,1.000000,36.000000,200.000000,50.000000,40.000000,66.000000,NaN,55.000000,8.000000,70.000000,NaN,40.000000,30.000000
25%,1000.750000,55.000000,212.000000,63.000000,57.000000,80.000000,NaN,76.000000,46.000000,76.000000,NaN,51.000000,40.000000
50%,2000.500000,71.000000,225.000000,74.000000,72.000000,93.500000,NaN,104.000000,77.000000,83.000000,NaN,62.000000,53.000000
75%,3000.250000,84.000000,237.000000,88.000000,85.000000,105.000000,NaN,224.250000,211.000000,90.000000,NaN,71.500000,67.000000
max,4000.000000,120.000000,250.000000,100.000000,120.000000,117.000000,NaN,250.000000,251.000000,120.000000,NaN,80.000000,80.000000

In [42]:
data.OPMD_repetitions.mean() #Gives us mean of a particular column

np.float64(111.88585365853659)

In [43]:
data.OPMD_repetitions.median() #Gives us median of a particular column

77.0

In [45]:
data.OPMD_repetitions.std() #gives us standard deviation of a column

83.43191486970808

In [48]:
data.isnull().sum() # gives us the no. of null values in each column

Serial_No                          0
DNA_Sample                         0
Huntington's_Disease               0
HD_repetitions                  2544
Fragile_x_syndrome                 0
FXS_repetitions                 3657
Myotonic_dystophy                  0
MD_repetitions                  3645
Dentatorubral-PA                   0
DPA_repetitions                 2575
Friedreich’s_Ataxia                0
FA_repetitions                  3598
Ataxia_Syndrome                    0
AS repetitions                  4000
AS_repetitions                  3296
OPMD                               0
OPMD_repetitions                2975
Spinocerebellar_Ataxia_Type8       0
SA8_repetitions                 3218
Spinocerebellar_Ataxia_Type4       0
SA4 repetitions                 4000
SA4_repetitions                 3053
Frontotemporal_Dementia            0
FD_repetitions                  3612
dtype: int64

In [51]:
data1 = data.dropna() # this is not useful fopr us as atleast 1 vlaue is null in a row

In [50]:
data1

Empty DataFrame
Columns: [Serial_No, DNA_Sample, Huntington's_Disease, HD_repetitions, Fragile_x_syndrome, FXS_repetitions, Myotonic_dystophy, MD_repetitions, Dentatorubral-PA, DPA_repetitions, Friedreich’s_Ataxia, FA_repetitions, Ataxia_Syndrome, AS repetitions, AS_repetitions, OPMD, OPMD_repetitions, Spinocerebellar_Ataxia_Type8, SA8_repetitions, Spinocerebellar_Ataxia_Type4, SA4 repetitions, SA4_repetitions, Frontotemporal_Dementia, FD_repetitions]
Index: []

[0 rows x 24 columns]

In [53]:
data_filled = data.fillna(0)

In [54]:
data_filled

,Serial_No,DNA_Sample,Huntington's_Disease,HD_repetitions,Fragile_x_syndrome,FXS_repetitions,Myotonic_dystophy,MD_repetitions,Dentatorubral-PA,DPA_repetitions,...,AS_repetitions,OPMD,OPMD_repetitions,Spinocerebellar_Ataxia_Type8,SA8_repetitions,Spinocerebellar_Ataxia_Type4,SA4 repetitions,SA4_repetitions,Frontotemporal_Dementia,FD_repetitions
0,1,GATAGGAACAGCCACTAGACCTCTGGTTGGTACCGTTACACGCGGT...,Not Found,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,...,68.0,Found,67.0,Not Found,0.0,Not Found,0.0,0.0,Not Found,0.0
1,2,AGGTTAGCTAGCCTATAGCTCGCGACCTATGTGGGAGACTAGAGCT...,Not Found,0.0,Not Found,0.0,Found,67.0,Not Found,0.0,...,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,0.0,Not Found,0.0
2,3,ACAATGAGCCGTCAACGAGCTCGACGAGTTCGACAACGAATTATCC...,Not Found,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,...,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,0.0,Found,76.0
3,4,AACCTGGTCCCCCTCCGAAGCTAAAGGGAATTGGACGTCGAGTAGG...,Not Found,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,...,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,0.0,Found,70.0
4,5,TCACGCTGCCTGGGAGAGCATATGAGCAGACAGCGTGTCAAGAGCG...,Not Found,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,...,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,0.0,Not Found,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3995,3996,ACGAGAATGCGTAATTACCGTGATCACAATATTCTGAGCAGTTCTC...,Found,85.0,Not Found,0.0,Not Found,0.0,Found,85.0,...,0.0,Not Found,0.0,Found,85.0,Not Found,0.0,0.0,Not Found,0.0
3996,3997,TATCGTGCTGACTGCTCTATACCCCTGTAAGAAATTGTTATTACGT...,Not Found,0.0,Not Found,0.0,Found,61.0,Not Found,0.0,...,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,0.0,Not Found,0.0
3997,3998,TGGAATCAAAGCATTCGTACCCGAACTGAGATCTCGCACGGCTTAC...,Not Found,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,...,0.0,Not Found,0.0,Not Found,0.0,Not Found,0.0,0.0,Not Found,0.0
3998,3999,GTGTACAGTGCGGGAGATGGGAAGGACTCCTAAAACGAGCCTCCGC...,Not Found,0.0,Found,239.0,Not Found,0.0,Not Found,0.0,...,239.0,Found,238.0,Not Found,0.0,Not Found,0.0,0.0,Not Found,0.0
3999,4000,AGCGGGTACCCCGGCAACGAGTCGTCGATGAACTACCTACAGCAGC...,Found,72.0,Not Found,0.0,Not Found,0.0,Found,72.0,...,0.0,Not Found,0.0,Found,72.0,Found,0.0,72.0,Not Found,0.0